version: 2

updates:
  - package-ecosystem: "gomod"
    directory: "/"
    schedule:
      interval: "monthly"
    labels:
      - "area: dependencies"
    commit-message:
      prefix: "chore"
      include: "scope"
    groups:
      all:
        patterns:
          - "*"
        exclude-patterns:
          - github.com/ardanlabs/kronk
      kronk:
        patterns:
          - github.com/ardanlabs/kronk


  - package-ecosystem: "gomod"
    directory: "/examples"
    schedule:
      interval: "monthly"
    labels:
      - "area: dependencies"
    commit-message:
      prefix: "chore"
      include: "scope"
    groups:
      all:
        patterns:
          - "*"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "monthly"
    labels:
      - "area: dependencies"
    commit-message:
      prefix: "chore"
      include: "scope"
    groups:
      all:
        patterns:
          - "*"
